In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

sns.set_style('whitegrid')

In [2]:
tf.__version__

'1.5.0'

In [3]:
hello = tf.constant('Hello ')
world = tf.constant('World')

In [5]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [6]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [7]:
print(result)

b'Hello World'


In [8]:
a = tf.constant(10)
b = tf.constant(20)

In [9]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [10]:
with tf.Session() as sess:
    result = sess.run(a + b)

In [11]:
result

30

In [12]:
const = tf.constant(10)

fill_mat = tf.fill((4, 4), 10)

In [14]:
myzeros = tf.zeros((4, 4))

In [15]:
myones = tf.ones((4, 4))

In [16]:
myrandn = tf.random_normal((4, 4), mean=0, stddev=1.0)

In [20]:
myrandu = tf.random_uniform((4, 4), minval=0, maxval=1)

In [21]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [22]:
sess = tf.InteractiveSession()

In [23]:
for op in my_ops:
    print(sess.run(op))
    print('='*30)

10
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[-0.42378595 -0.83003181 -0.62338614 -0.23820399]
 [ 1.25634313  0.74318248 -0.2089262  -1.63175082]
 [-1.24282861 -1.56997645 -0.10051653 -0.60684884]
 [-0.84287626  0.21149538  0.18386181 -0.09061545]]
[[ 0.34293938  0.84738433  0.83768034  0.71266913]
 [ 0.40233934  0.26822889  0.87815464  0.69708836]
 [ 0.73321426  0.73844528  0.08813643  0.34623337]
 [ 0.44017088  0.20880508  0.14533341  0.77030277]]


In [24]:
a = tf.constant([[1, 2],
                [3, 4]])

In [25]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])